import sys
sys.path.insert(0, ".")
from services.nlp_to_sql import convert_to_sql, has_recognizable_keywords

prompts = [
    # 1. Basic SELECT
    "Show all employees.",
    "Display all students.",
    "List all projects.",
    "Show all subjects.",
    "Display the names and salaries of all employees.",
    "Show the names, marks, and CGPA of all students.",
    "List employees who work in the IT department.",
    "Show students from Bangalore.",
    "Display employees whose salary is greater than 60000.",
    "Show students who scored more than 80 marks.",
    # 2. WHERE condition
    "Find employees older than 30.",
    "Find employees younger than 30 who work in IT.",
    "Show employees from Bangalore.",
    "Find students whose CGPA is above 8.5.",
    "Show students whose marks are between 70 and 90.",
    "Find employees with more than 5 years of experience.",
    "Show students studying in semester 5.",
    "Find employees whose performance rating is greater than 4.",
    "Show students who have received a scholarship.",
    "Find employees who joined before 2020.",
    # 3. ORDER BY
    "Display employees in descending order of salary.",
    "Show students in ascending order of CGPA.",
    "List employees from highest to lowest performance rating.",
    "Display students according to their marks from highest to lowest.",
    "Show employees ordered by their experience.",
    "Display the 5 highest-paid employees.",
    "Show the 3 students with the highest CGPA.",
    # 4. Aggregate functions
    "What is the average salary of employees?",
    "Find the maximum salary among employees.",
    "Find the minimum salary among employees.",
    "Calculate the total salary paid to all employees.",
    "Count the number of employees.",
    "Count the number of students.",
    "Find the average CGPA of students.",
    "Find the highest marks obtained by a student.",
    "Find the average performance rating of employees.",
    # 5. GROUP BY
    "Count employees in each department.",
    "Find the average salary of each department.",
    "Find the maximum salary in each department.",
    "Find the minimum salary in each department.",
    "Count students from each city.",
    "Find the average CGPA for each city.",
    "Find the average marks for each subject.",
    "Count employees based on gender.",
    "Count students based on semester.",
    "Find the average performance rating for each department.",
    # 6. HAVING
    "Display departments having more than 3 employees.",
    "Show departments where the average salary is greater than 60000.",
    "Display cities having more than 3 students.",
    "Show departments where the maximum salary is above 80000.",
    "Find departments where the average performance rating is greater than 4.",
    "Display semesters having more than 3 students.",
    "Show departments whose total salary exceeds 200000.",
    "Display cities where the average CGPA is greater than 8.",
    "Display departments that have more employees than the average number of employees per department.",
    # 7. NULL prompts
    "Show employees who do not have a manager.",
    "Find employees who have a manager.",
    "Display students whose email is NULL.",
    "Show students who have a phone number.",
    "Find employees whose manager ID is NULL.",
    "Display students who have no guardian ID.",
    "Show employees whose manager ID is not NULL.",
    # 8. JOIN prompts
    "Show each project along with the name of its lead employee.",
    "Display project names and the department of their lead employees.",
    "Show employees who are leading projects.",
    "Display the names of employees and the projects they lead.",
    "Find projects led by employees from the IT department.",
    "Show the salary of each employee who is leading a project.",
    "Show each student's name and the subject they are taking.",
    "Display student names along with subject names.",
    "Find students taking Mathematics.",
    "Show students taking Computer Science.",
    "Display each subject and the student taking it.",
    "Show the marks of students along with their subject names.",
    # 9. Multi-condition JOIN
    "Show the names of employees who lead projects with a deadline after 2026-04-01.",
    "Find employees from IT who are leading projects.",
    "Show project names, employee names, and their salaries.",
    "Display students from Bangalore who are taking Mathematics.",
    "Show students with CGPA above 8 who are taking Computer Science.",
    "Display the names and marks of students taking Science.",
    # 10. Subquery prompts
    "Find employees earning more than the average employee salary.",
    "Find students whose CGPA is greater than the average CGPA.",
    "Show employees who earn the highest salary.",
    "Find students who obtained the highest marks.",
    "Find employees with salary greater than the salary of Amit.",
    "Find students whose CGPA is higher than Rahul's CGPA.",
    "Display employees who have more experience than the average experience.",
    "Find departments whose average salary is greater than the overall average salary.",
    "Find employees working in the department with the highest average salary.",
    # 11. EXISTS / NOT EXISTS
    "Find employees who lead at least one project.",
    "Find employees who do not lead any project.",
    "Show students who are taking at least one subject.",
    "Find students who are not taking any subject.",
    "Find departments that have at least one employee earning more than 80000.",
    "Find employees who lead a project with a deadline after 2026-05-01.",
    # 12. ANY / ALL
    "Find employees whose salary is greater than ANY employee in the HR department.",
    "Find employees whose salary is greater than ALL employees in the HR department.",
    "Find students whose marks are greater than ALL students taking Science.",
    "Find employees whose experience is greater than ANY employee in the IT department.",
    "Find employees whose salary is less than ALL employees in Finance.",
    # 13. CASE / conditional prompts
    "Categorize employees as: High salary if salary > 70000 Medium salary if salary between 50000 and 70000 Low salary otherwise.",
    "Display students and classify their CGPA as Excellent, Good, or Average.",
    "Show employees and label their performance as Excellent if rating >= 4.5, otherwise Good.",
    # 14. Best 15 prompts
    "Show all employees from the IT department.",
    "Find employees whose salary is greater than 70000.",
    "Display the top 5 highest-paid employees.",
    "Find the average salary of each department.",
    "Display departments having more than 3 employees.",
    "Find employees who do not have a manager.",
    "Find employees earning more than the average employee salary.",
    "Show each project along with the name of its lead employee.",
    "Find employees who are not leading any project.",
    "Show students from Bangalore who have a CGPA greater than 8.",
    "Display students along with the subjects they are taking.",
    "Find students who are not taking any subject.",
    "Find employees whose salary is greater than ALL employees in the HR department.",
    "Display departments whose average salary is greater than the overall average salary.",
    "Show the project name, lead employee name, department, and salary for projects led by IT employees.",
]

for i, q in enumerate(prompts, 1):
    sql = convert_to_sql(q)
    rec = has_recognizable_keywords(q)
    print(f"{i:03d}. {q}")
    print(f"    recog={rec} SQL: {sql}")
    print()